name: roboshop
services:
  mongodb:
    build: ./mongodb
    image: venkat/mongodb:v1
    container_name: mongodb 
  catalogue:
    build: ./catalogue
    image: venkat/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  frontend:
    build: ./frontend
    image: venkat/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
  user:
    build: ./user
    image: venkat/user:v1
    container_name: user
    environment:
      MONGO: true
      REDIS_URL: 'redis://redis:6379'
      MONGO_URL: "mongodb://mongodb:27017/users"
    depends_on:
    - redis
    - mongodb
  cart:
    build: ./cart
    image: venkat/cart:v1
    container_name: cart
    environment:
      REDIS_HOST: redis
      CATALOGUE_HOST: catalogue
      CATALOGUE_PORT: 8080
    depends_on:
    - redis
    - catalogue
  shipping:
    build: ./shipping
    image: venkat/shipping:v1
    container_name: shipping
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: mysql
    depends_on:
    - mysql
    - cart
  redis:
    image: redis:7
    container_name: redis 
  mysql:
    image: venkat/mysql:v1
    build: ./mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "RoboShop@1"
networks:
  default:
    name: roboshop
    driver: bridge
    external: false